name: video-format-converter
services:
- name: web
  source_dir: /
  github:
    repo: your-username/NewVideoFormatConverter
    branch: main
  run_command: python app.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: professional-xs
  routes:
  - path: /
  health_check:
    http_path: /health
  envs:
  - key: PORT
    value: "8080"
  - key: FLASK_ENV
    value: "production"
  - key: FFMPEG_BINARY
    value: "/usr/bin/ffmpeg"
  - key: FFPROBE_BINARY
    value: "/usr/bin/ffprobe"
  build_command: |
    apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt 