services:
  - type: web
    name: video-format-converter
    env: python
    buildCommand: pip install -r requirements.txt && python setup_fonts.py
    startCommand: python app.py
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: PYTHONWARNINGS
        value: ignore
    autoDeploy: true
